project:
  type: website

website:
  title: "AIBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

comments:
  giscus:
    repo: CarstenLange/AIBlog

editor: visual

